### ISSUE TITLE
append new files in another form

### ISSUE THREAD

**Issue by liongkj** [chungchunwang/Budibase-File-Upload#1]
Hi, i have this condition that I may need to add new supplementary files in a 'update' form. How do i do this?

**Comment by chungchunwang** [comment]
Hi! You can just add the file upload component to the update form component. For example, if you generate the CRUD pages for your table, just replace the text field in the update form with the file upload component.

**Comment by liongkj** [comment]
I thought that will 'replace' the old files?

For example
During create, i added file A, file B.
later on in update, I wanted to add file C.

**Comment by chungchunwang** [comment]
Hi! No, it will not replace existing files.
