### ISSUE TITLE
Decode Serialized JSON Back to Binary Object After Upload

### ISSUE THREAD

**Issue by chadgriff** [chungchunwang/Budibase-File-Upload#11]
I have a use case where when a user uploads a file using the Budibase-File-Upload plugin, I would like to send out an email with the same file attached to it.  I am using an MS SQL database with a nvarchar(max) field configured to accept the JSON string.  Is there a way to pull the string into some Javascript that can decode it back into a file?  All of the files involved with this use case would be .pdf files.

**Comment by chungchunwang** [comment]
Hi, take a look at the source code for the corresponding File Repeater plugin. The string is decoded back into a file there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Chad Griffith ***@***.***>
Sent: Monday, September 18, 2023 6:51:46 PM
To: chungchunwang/Budibase-File-Upload ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chungchunwang/Budibase-File-Upload] Decode Serialized JSON Back to Binary Object After Upload (Issue #11)


I have a use case where when a user uploads a file using the Budibase-File-Upload plugin, I would like to send out an email with the same file attached to it. I am using an MS SQL database with a nvarchar(max) field configured to accept the JSON string. Is there a way to pull the string into some Javascript that can decode it back into a file? All of the files involved with this use case would be .pdf files.

**Comment by chungchunwang** [comment]
The repo is here: https://github.com/chungchunwang/Budibase-File-Repeater
