### ISSUE TITLE
Import a Date

### ISSUE THREAD

**Issue by markusthiel** [chungchunwang/Budibase-File-Upload#12]
Would be Great if it was possible to configure the String of a Date Field Like:
DD.MM.YYYY or YYYY-MM-DD. I cant Import my excel List because i have a Date in german Style. But it also does Not Work of i convert it, i dont know how it has to Look.

**Comment by chungchunwang** [comment]
Hi, is the regarding the file upload plugin? I don't maintain the date field. If not, I think you should try to post this in the Budibase repository.

**Comment by chungchunwang** [comment]
Closing for now given this is likely not regarding this repo.
Feel free to reopen!
