### ISSUE TITLE
Falied to load resource

### ISSUE THREAD

**Issue by jpgalvao63** [chungchunwang/Budibase-File-Upload#14]
I've made 2 screens to CRUD my files.
On the update screen when i try to view data for update i receice the error on the screen.
Can you help ?
![UpdateAttachFile2](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/921d6a1c-774b-451a-8af3-c2fbe78bd449)

**Comment by jpgalvao63** [comment]
![UpdateAttachFile](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/9bfcefa8-7ac8-4014-be65-5ece94a85922)

**Comment by jpgalvao63** [comment]
I've trye tu follow the example on the plugin page and still error

![Attachv2_1](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/8e59c5e1-23fe-445c-937f-f6de71b966c3)
![Attachv2_2](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/9fa14d0f-91d7-492f-bb32-68f271601552)
![Attachv2_3](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/55755fc3-2877-496f-8070-58445ac9e74f)
![Attachv2_4](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/95d3f8d4-a97e-4651-bab8-dcdc8febceb6)

**Comment by chungchunwang** [comment]
Hi, what field are you storing the file in? From what I can tell from the screenshots it seems that the repeater is parsing the title field. 

Consider checking if the repeater component is referencing the file field.

Hope this helps! If not, feel free to continue this thread.

**Comment by jpgalvao63** [comment]
Hello, Thanks for the answer.

This is the table structure in MySQL

![Attachv2_5](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/795c3782-cfd3-43e8-a49c-c958b6c085fd)

This is the configuration you sugested

![Attachv2_7](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/8c362210-454e-4819-ad26-b0bc00acc79c)

This is the result

![Attachv2_6](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/ed45bf1a-9bd2-4468-a831-e14afd6d5e92)

Can it be on the document upload, the problem ?

**Comment by chungchunwang** [comment]
Hi, I think this configuration should be correct.

Maybe it's an issue with the encoding protection option; ensure it is turned on for both the repeater and the uploader.

After you make this change, you might want to clear out all the past rows, as it may be formatted incorrectly after the change.

**Comment by chungchunwang** [comment]
To help me debug, could you send a sample of what the file field causing this error looks like?

It seems like the string encoding of the files are malformed.

**Comment by jpgalvao63** [comment]
Is this what you need ?

{"type":"Buffer","data":[46,91,123,34,110,97,109,101,34,58,34,65,116,116,97,99,104,118,50,95,53,46,80,78,71,34,44,34,116,121,112,101,34,58,34,105,109,97,103,101,47,112,110,103,34,44,34,115,105,122,101,34,58,51,57,48,54,44,34,108,105,110,107,34,58,34,100,97,116,97,58,105,109,97,103,101,47,112,110,103,59,98,97,115,101,54,52,44,105,86,66,79,82,119,48,75,71,103,111,65,65,65,65,78,83,85,104,69,85,103,65,65,65,81,115,65,65,65,67,104,67,65,89,65,65,65,68,81,112,90,112,117,65,65,65,65,65,88,78,83,82,48,73,65,114,115,52,99,54,81,65,65,65,65,82,110,81,85,49,66,65,65,67,120,106,119,118,56,89,81,85,65,65,65,65,74,99,69,104,90,99,119,65,65,68,115,77,65,65,65,55,68,65,99,100,118,113,71,81,65,65,65,55,88,83,85,82,66,86,72,104,101,55,90,48,55,106,116,119,52,69,69,66,57,67,74,57,109,99,108,43,108,81,119,79,43,120,81,75,84,84,79,74,119,111,122,109,66,107,119,69,77,53,51,115,65,90,119,118,55,65,65,55,50,68,108,111,86,82,86,76,70,98,53,100,54,87,105,50,49,43,106,49,65,110,112,98,52,69,99,101,89,101,105,73,112,83,118,49,104,65,65,65,119,103,67,119,65,119,65,83,121,65,65,65,84,121,65,73,65,84,67,65,76,65,68,67,66,76,65,68,65,66,76,73,65,65,66,80,73,65,103,66,77,73,65,115,65,77,73,69,115,65,77,65,69,115,103,65,65,69,56,103,67,65,69,119,103,67,119,65,119,103,83,119,65,119,65,83,121,65,65,65,84,121,65,73,65,84,67,65,76,65,68,67,66,76,65,68,65,66,76,73,65,65,66,80,73,65,103,66,77,73,65,115,65,77,76,70,80,87,102,120,54,71,90,52,43,102,66,103,43,80,76,48,77,118,47,121,104,104,76,102,84,56,69,72,83,84,50,47,43,119,69,114,56,57,51,88,52,57,78,102,72,52,101,80,102,88,52,102,102,47,116,68,100,56,79,47,110,52,97,79,48,47,100,116,51,102,119,68,103,102,97,119,111,105,55,102,104,74,65,72,100,50,76,112,120,102,109,78,90,47,80,55,110,48,120,82,89,99,102,115,56,117,66,68,98,113,121,121,67,67,80,81,50,116,118,70,55,43,68,49,69,69,77,103,67,114,115,120,78,101,104,97,47,88,112,54,87,66,102,99,78,90,102,72,57,109,119,43,50,71,70,83,47,104,54,57,47,43,47,50,57,121,54,76,88,76,109,81,66,86,50,89,55,87,81,81,104,113,79,51,112,120,97,115,104,121,117,73,48,110,74,52,113,54,98,107,115,56,114,114,105,101,85,76,118,53,106,82,43,113,104,67,118,48,76,52,110,69,102,107,43,102,69,53,107,56,88,110,52,76,65,74,120,101,84,56,79,110,47,55,120,73,82,114,83,49,86,97,107,116,99,111,75,116,82,55,67,88,53,43,71,114,47,47,53,57,76,122,43,69,80,103,116,87,87,104,66,53,76,74,111,49,84,85,83,104,86,108,74,65,119,104,115,75,52,115,105,113,74,56,71,53,52,77,89,47,72,53,47,55,70,43,56,79,71,110,52,102,83,50,76,107,78,102,88,70,99,52,49,105,97,85,118,105,122,106,56,97,65,86,72,68,76,65,81,119,75,78,69,51,76,52,97,112,115,83,121,73,99,51,110,116,90,84,86,43,54,70,72,107,53,102,51,57,89,101,50,79,116,107,115,108,85,87,110,114,113,82,101,73,102,109,100,65,71,90,50,77,119,120,53,79,48,108,81,43,55,109,77,50,76,79,89,104,121,71,74,66,74,81,115,107,110,76,67,103,105,70,75,79,81,84,74,67,69,69,87,103,122,73,76,54,73,120,81,51,43,100,47,120,53,48,122,90,89,115,103,122,100,75,84,117,111,83,97,67,78,83,87,83,69,84,110,71,84,47,51,54,111,114,47,66,55,48,104,68,99,68,73,112,114,73,73,103,97,54,51,83,50,86,82,98,75,51,53,68,111,87,53,90,57,71,82,82,81,119,50,116,86,108,107,85,81,82,119,73,55,51,89,112,76,52,81,55,72,109,65,110,53,70,70,115,85,110,53,48,69,54,49,122,81,73,68,109,78,108,77,70,105,72,73,119,122,122,69,49,88,111,87,83,119,103,66,100,88,98,79,111,104,47,119,73,98,103,83,65,86,121,55,90,54,71,53,85,66,98,86,117,104,82,82,75,110,109,57,65,67,79,98,121,50,73,54,70,79,89,107,87,114,76,73,53,104,53,113,99,120,97,54,74,121,72,72,88,69,86,110,74,106,104,72,89,111,66,73,103,68,108,56,48,67,54,81,120,82,83,69,73,99,48,109,105,122,76,103,71,51,77,101,79,110,68,108,109,66,90,66,72,116,81,78,87,102,84,113,43,118,55,78,110,121,56,99,67,50,85,65,77,114,97,100,52,72,83,66,76,78,118,84,56,70,83,84,82,98,75,70,121,99,54,82,102,70,54,105,108,116,56,111,67,121,69,79,82,43,75,87,84,85,75,50,65,106,54,107,117,43,51,84,56,71,109,74,76,79,82,73,99,116,53,81,118,104,75,56,101,114,116,69,70,107,75,106,114,105,106,76,115,79,86,49,65,110,104,117,73,103,115,119,85,77,103,70,89,70,56,103,105,56,48,73,119,119,54,117,54,110,65,102,73,65,115,65,77,73,69,115,65,77,65,69,115,103,65,65,69,56,103,67,65,69,119,103,67,119,65,119,103,83,119,65,119,65,83,121,65,65,65,84,121,65,73,65,84,67,65,76,65,68,67,66,76,65,68,65,66,76,73,65,65,66,80,73,65,103,66,77,73,65,115,65,77,73,69,115,65,77,65,69,115,103,65,65,69,56,103,67,65,69,122,115,87,120,89,76,88,117,115,80,65,79,116,121,69,49,110,69,100,51,68,71,114,102,57,79,122,65,105,121,65,78,103,78,113,56,115,105,102,113,57,72,68,72,106,47,74,109,43,76,65,74,65,70,119,71,53,89,86,120,89,104,50,73,117,101,120,78,116,119,105,103,73,73,98,43,65,79,87,43,77,116,51,115,85,114,47,49,116,102,97,88,105,97,54,53,79,56,43,115,51,102,52,90,121,120,114,115,90,51,113,89,53,69,121,89,88,78,108,98,87,57,76,82,122,103,105,75,119,113,105,43,112,88,65,71,106,77,65,108,103,103,67,120,47,73,77,100,104,100,47,105,120,118,70,69,103,81,85,121,113,66,53,65,117,78,66,77,109,80,76,79,68,66,87,86,85,87,53,82,65,107,112,81,106,75,107,101,84,89,82,84,50,76,54,86,120,112,51,81,49,90,78,79,112,75,82,81,77,65,119,113,89,57,105,53,111,115,107,113,67,47,117,105,120,97,51,51,106,87,107,73,110,97,107,106,89,67,80,67,67,98,122,108,110,85,90,74,69,99,50,48,111,87,67,110,111,90,65,66,80,114,121,109,75,107,72,73,114,52,119,72,84,55,102,103,55,65,74,73,66,56,118,105,68,115,88,49,56,87,98,121,99,108,106,90,67,51,50,103,97,65,120,50,70,49,87,81,103,104,99,79,100,78,66,49,115,73,119,76,67,112,81,71,48,73,73,79,83,98,118,104,57,49,68,86,108,77,101,101,77,87,56,121,69,76,101,70,120,117,73,103,115,65,117,72,43,81,66,81,67,89,81,66,89,65,89,65,74,90,65,73,67,74,65,56,107,105,117,53,77,67,116,43,72,80,106,43,72,53,43,99,102,119,120,43,47,67,99,100,109,116,76,77,73,100,67,88,57,122,119,120,72,118,104,117,105,68,69,87,83,120,67,84,49,90,87,69,82,105,107,115,50,102,52,99,102,122,56,47,68,68,90,67,84,74,43,50,88,52,107,116,102,53,56,51,88,52,56,109,85,56,55,114,98,88,52,97,99,47,72,74,70,50,120,80,81,115,106,48,118,84,90,82,114,110,79,68,104,51,74,89,115,43,121,71,73,84,84,77,72,43,88,104,98,73,119,114,88,110,101,81,122,117,83,118,52,105,54,66,86,90,50,112,56,102,122,55,77,77,115,114,83,102,114,54,77,111,88,113,117,49,72,74,112,100,121,113,74,99,108,121,72,98,97,88,106,76,49,108,76,69,57,82,76,74,104,105,120,117,105,112,102,70,68,119,107,103,100,48,86,87,81,101,114,84,112,116,50,102,119,50,116,121,53,102,98,53,81,112,53,109,80,102,52,113,114,115,118,71,79,107,115,107,121,74,47,72,103,104,76,81,56,106,77,104,67,47,113,69,80,69,51,118,113,56,43,74,82,66,54,77,43,43,112,90,97,70,108,69,85,89,81,70,85,118,81,115,78,115,69,70,48,112,99,104,88,71,105,76,75,55,76,55,80,65,88,56,72,76,119,105,106,111,111,115,86,68,49,117,50,66,67,68,48,116,113,122,85,80,110,105,117,82,88,117,72,79,43,81,82,100,75,109,120,43,78,117,90,90,71,117,48,66,83,81,120,83,98,107,81,90,107,72,87,82,83,66,68,116,75,71,76,80,74,54,52,114,53,82,70,117,102,75,70,79,49,81,90,71,110,74,85,77,79,108,110,101,47,86,72,74,50,55,108,85,87,90,106,105,119,50,73,81,108,81,81,85,83,81,121,97,75,52,73,113,56,106,67,57,101,114,67,85,72,116,116,50,81,111,73,110,86,50,90,97,72,75,53,109,49,120,53,97,97,104,86,68,71,56,101,82,68,111,87,99,68,55,113,65,86,53,76,111,115,56,122,121,113,121,97,80,81,107,56,106,113,55,115,106,67,107,117,99,57,113,117,80,82,65,55,70,89,87,112,81,120,71,97,110,77,87,120,85,78,101,121,79,75,109,90,65,70,90,100,78,57,100,50,110,82,70,106,103,72,109,65,109,54,74,76,75,90,54,117,119,71,97,108,51,99,111,75,81,110,117,118,79,43,85,104,100,117,86,72,107,119,106,55,52,72,90,114,83,122,109,110,107,76,89,121,114,115,104,54,86,50,84,55,67,108,85,117,65,48,117,107,68,114,100,57,55,67,118,49,122,109,77,80,89,68,107,83,105,49,53,100,70,54,104,116,108,56,55,104,56,99,70,99,77,85,109,56,97,54,73,97,90,50,70,84,82,97,67,107,43,75,68,67,87,79,88,115,112,103,70,56,76,52,78,100,107,111,117,65,114,103,76,105,67,105,52,67,100,79,86,117,72,78,108,104,57,50,68,76,65,68,65,120,72,51,74,81,105,89,49,52,52,81,109,100,76,72,56,88,49,51,106,47,53,77,104,120,99,79,65,76,72,97,68,84,79,104,101,99,88,74,87,47,49,43,49,47,116,47,87,108,111,86,70,74,67,98,90,71,66,100,108,119,97,111,103,105,57,50,119,111,105,120,97,114,67,50,76,113,52,69,115,57,115,67,79,90,90,72,100,79,112,85,47,97,118,47,72,47,101,73,88,98,79,110,98,112,80,110,68,90,51,70,57,82,113,102,77,82,79,101,70,119,85,107,98,49,72,71,112,56,56,78,112,101,70,72,110,108,76,117,53,89,83,70,90,121,78,116,115,48,56,105,99,86,52,54,47,90,98,101,74,120,121,48,71,99,97,99,78,56,102,102,121,122,56,101,52,100,111,87,56,52,120,98,113,56,72,110,106,53,49,113,101,83,47,71,121,50,77,117,68,90,76,65,101,117,53,87,70,67,54,90,107,43,101,97,73,47,48,79,80,104,50,88,100,82,101,50,80,51,101,88,122,103,100,85,116,77,119,88,105,72,77,81,105,106,106,107,103,112,81,48,120,84,90,102,122,100,83,90,112,53,57,113,108,50,53,83,107,106,54,74,119,66,43,115,57,105,51,78,116,109,80,43,76,112,116,56,108,55,107,117,54,122,117,115,43,100,47,74,99,105,103,84,53,71,77,68,122,79,113,119,116,72,121,83,68,78,100,109,112,76,67,82,111,75,54,47,98,122,47,43,52,109,51,47,115,75,118,66,54,90,101,82,122,99,104,52,116,105,55,119,78,75,117,49,99,79,47,74,57,104,50,112,84,84,83,89,54,80,98,75,119,68,84,113,118,84,103,43,102,101,51,107,117,74,81,114,66,52,52,76,101,51,120,112,78,82,75,66,118,108,54,54,120,51,66,118,87,90,112,43,121,121,80,43,111,65,47,107,102,100,55,97,102,114,43,103,56,71,57,104,70,48,71,98,66,71,79,116,97,85,75,101,103,57,113,116,116,71,108,80,48,115,71,79,54,48,108,100,107,115,97,81,78,43,101,43,105,48,56,80,110,88,112,53,76,121,89,80,99,105,83,67,84,120,89,48,101,74,73,78,49,79,89,52,115,74,66,66,105,109,81,85,57,105,121,82,89,108,67,122,99,53,48,111,98,104,70,54,100,81,116,104,118,116,85,110,104,90,79,76,75,87,110,111,87,67,109,115,98,57,79,100,122,90,83,54,104,70,117,83,49,110,111,88,79,103,121,122,117,107,112,48,79,81,47,121,86,100,120,54,81,84,51,84,43,50,70,51,81,104,102,120,121,51,78,81,76,107,71,68,77,120,118,66,82,70,117,73,102,80,90,56,104,43,122,53,119,117,51,87,79,43,80,50,51,82,112,116,43,118,90,120,109,75,89,104,81,102,66,52,53,88,47,52,114,109,57,118,103,102,112,101,53,55,98,79,69,51,73,55,80,50,56,108,122,75,86,109,81,98,47,89,103,71,97,122,79,98,105,99,52,120,122,47,108,83,82,105,104,43,121,49,82,49,65,106,75,97,88,56,75,102,74,102,51,54,84,83,99,76,68,48,76,119,86,51,57,81,55,109,110,114,69,100,84,97,89,77,55,102,75,98,79,117,78,57,111,107,122,54,110,80,112,43,85,105,47,108,68,102,99,89,50,67,75,114,101,112,49,69,113,77,86,51,110,98,101,87,53,70,66,102,52,106,84,115,86,79,117,66,88,102,112,65,77,49,109,102,72,115,116,105,65,87,103,68,67,57,99,108,70,65,72,102,66,119,56,116,67,117,118,110,104,83,112,116,99,53,101,71,113,56,67,68,90,47,85,80,80,65,103,66,77,73,65,115,65,77,72,69,77,87,84,68,88,99,68,121,117,79,75,57,120,110,100,102,103,84,88,100,48,72,118,86,108,118,99,74,79,90,86,70,90,99,120,67,70,48,69,117,68,119,51,65,116,87,98,105,55,75,65,49,82,117,68,115,48,79,109,49,97,108,106,55,80,114,85,122,98,102,77,116,87,114,81,57,53,81,79,53,72,70,104,70,107,56,82,66,99,83,82,89,121,115,86,114,116,68,84,105,74,53,74,79,116,107,121,120,54,54,122,108,97,55,47,112,56,66,72,89,111,105,50,120,100,103,87,119,105,65,105,99,69,87,97,118,81,83,103,117,121,48,79,86,98,119,111,72,114,85,65,107,117,118,55,84,55,112,43,118,54,122,49,102,110,71,76,66,101,65,116,80,84,112,83,70,81,115,121,117,54,83,67,76,74,74,57,116,56,82,90,43,71,70,88,80,43,100,116,50,116,110,107,65,52,76,106,43,88,121,87,73,113,113,56,115,56,68,111,99,98,104,106,83,102,48,111,82,49,69,68,109,111,54,75,112,101,121,100,49,86,88,75,51,89,72,65,78,99,66,50,83,121,54,106,79,81,53,121,117,101,76,47,72,48,54,112,98,57,111,111,119,87,81,108,48,87,87,107,82,53,115,54,89,56,78,81,69,100,110,52,80,74,81,108,90,77,54,114,85,83,54,102,74,109,87,65,77,100,99,79,71,75,55,88,89,85,75,115,67,75,65,71,53,99,113,102,78,56,49,99,65,88,79,110,86,110,73,104,78,83,109,90,51,112,74,98,103,53,106,102,76,51,107,84,112,75,105,82,121,102,89,56,108,67,102,117,111,104,67,107,79,82,109,120,67,68,74,55,118,54,112,56,79,70,82,107,68,76,47,103,87,121,77,78,86,100,121,75,76,115,79,83,84,108,67,54,98,56,117,82,105,81,120,97,54,52,86,115,56,67,98,111,73,80,83,103,110,103,71,69,84,117,113,104,119,107,48,76,110,54,88,121,75,76,74,88,88,114,47,89,73,122,80,81,117,88,110,111,116,66,110,101,47,66,50,75,107,115,112,114,109,72,53,65,110,77,75,73,84,122,97,100,87,110,78,71,70,70,112,117,72,72,56,47,77,99,101,77,108,100,65,121,101,69,82,107,67,55,52,66,117,118,55,118,109,108,117,104,80,52,57,114,113,110,100,114,85,68,79,53,78,70,49,104,78,120,53,121,108,107,99,48,52,119,120,50,87,51,115,110,65,67,67,69,79,74,77,77,84,119,81,117,105,109,106,102,57,87,110,57,75,69,86,83,107,110,75,97,101,114,115,117,118,109,106,120,74,53,98,99,53,90,67,70,52,89,73,98,47,85,48,53,72,70,107,114,114,84,79,89,113,99,76,80,67,108,102,75,106,88,98,97,85,85,69,108,69,57,71,80,117,86,66,99,65,49,99,65,75,52,86,107,57,65,53,78,76,114,113,82,119,98,90,65,71,72,120,47,85,71,51,105,50,77,113,84,102,84,55,113,85,99,72,50,81,66,65,67,90,50,76,65,118,49,108,113,110,101,50,54,70,103,87,121,114,122,66,70,101,106,86,55,102,108,118,71,117,50,55,81,72,90,114,83,121,83,117,120,112,66,69,115,104,105,102,121,67,76,104,50,71,110,115,113,105,115,112,82,67,81,120,102,53,65,70,103,47,68,76,109,85,104,118,89,112,52,54,49,78,87,89,76,55,86,101,104,98,54,70,105,109,114,78,68,100,68,66,54,82,56,106,114,99,100,49,86,48,68,110,54,102,54,70,89,99,79,100,83,116,85,112,47,102,75,88,101,87,56,115,73,84,55,54,70,108,85,104,105,72,74,77,73,85,72,120,114,89,106,66,117,50,48,86,105,73,117,81,90,65,70,84,108,107,119,86,57,78,56,117,102,82,53,68,83,85,76,86,83,53,90,74,72,88,66,101,101,117,76,114,77,68,75,110,99,113,67,66,56,90,50,81,119,106,97,71,76,121,66,76,79,104,49,109,116,53,51,65,97,49,118,97,53,52,112,70,47,75,71,116,68,121,80,116,84,119,115,53,106,53,108,73,84,47,106,77,73,87,104,121,75,97,69,103,69,120,54,67,52,75,54,52,116,101,67,78,117,119,88,53,84,114,66,55,116,73,121,87,83,119,53,114,121,52,80,105,122,108,73,122,119,73,50,73,119,83,107,47,70,122,83,81,119,106,55,49,89,66,101,50,76,78,89,99,108,53,107,99,84,72,72,109,76,77,89,52,89,71,120,106,89,103,66,101,87,98,117,73,65,47,97,117,67,47,66,114,99,113,53,103,75,52,72,101,47,76,56,121,81,88,110,76,90,57,102,103,83,88,99,114,83,121,109,80,71,111,89,119,103,78,106,50,54,65,68,48,103,86,54,117,80,79,103,114,117,66,90,48,66,98,55,69,117,67,104,51,72,80,50,49,89,97,120,80,107,108,114,49,78,69,55,98,54,115,56,76,71,97,110,115,111,67,72,74,82,99,74,55,65,90,107,65,90,118,106,104,103,101,49,110,103,72,115,67,109,81,66,65,67,97,81,66,81,67,89,50,76,69,115,78,110,55,113,57,74,98,110,103,112,73,114,122,108,49,99,53,51,48,87,80,97,89,55,79,107,100,47,49,56,86,117,90,88,72,98,112,48,54,122,117,121,56,67,115,116,105,87,97,56,110,67,51,82,72,82,111,112,103,67,117,122,49,72,111,116,79,88,112,118,108,98,118,103,100,108,112,55,75,111,66,75,43,65,76,66,54,72,75,56,109,105,101,65,102,110,87,79,43,114,50,107,43,102,70,54,109,115,50,90,103,88,103,72,84,83,74,108,120,100,66,49,55,72,115,85,116,90,118,79,117,112,85,53,47,110,74,100,89,120,112,47,49,54,101,102,76,72,112,109,51,113,117,87,84,114,78,87,82,84,53,54,114,86,65,52,69,115,103,65,83,47,75,71,114,102,88,49,43,111,107,68,75,120,72,90,74,102,57,82,106,77,97,89,69,115,122,56,71,52,106,53,53,70,107,73,83,83,82,102,79,112,85,56,107,122,66,118,99,56,122,84,69,75,73,113,82,112,88,76,53,119,106,107,98,80,81,116,87,84,110,65,78,109,115,105,116,115,57,87,51,97,76,114,68,85,113,115,119,120,119,76,86,103,113,105,115,114,56,51,120,101,81,107,88,99,57,43,113,87,47,86,111,90,82,100,75,122,99,79,85,98,81,117,105,108,82,85,82,54,120,120,50,75,51,75,107,115,79,107,43,100,120,106,121,66,49,104,79,112,43,104,119,78,87,101,104,54,105,110,112,104,81,108,57,78,87,49,100,121,70,85,82,70,65,68,101,117,120,110,109,43,111,108,121,103,85,51,100,108,113,74,65,105,53,56,55,107,107,114,82,70,47,84,54,57,78,73,87,73,114,51,118,75,79,43,89,43,90,83,69,47,119,53,65,104,98,106,90,90,112,69,77,82,90,72,69,78,89,111,66,107,86,47,57,48,117,78,65,73,54,67,73,73,80,98,86,56,83,43,118,117,121,109,73,83,82,84,54,102,48,101,119,57,57,78,73,85,121,79,76,109,76,79,49,90,75,71,112,66,72,118,76,75,85,67,75,87,111,50,100,120,78,88,120,81,83,103,68,72,81,74,70,106,77,90,103,54,86,47,57,71,48,70,88,122,104,102,48,108,100,101,118,57,83,78,97,106,105,77,106,120,108,104,66,54,97,81,71,71,73,82,116,119,84,104,89,83,57,52,50,110,84,114,79,103,100,106,48,74,80,47,71,103,80,55,116,56,113,115,99,104,57,99,88,53,67,83,71,88,81,55,52,80,105,113,108,76,102,104,57,102,88,57,103,83,104,84,67,49,74,97,89,108,80,90,78,101,87,105,65,84,121,115,71,52,87,49,108,77,101,100,81,119,74,74,71,65,79,112,52,69,117,80,82,73,119,118,72,84,99,77,114,80,111,99,118,107,99,115,106,51,73,97,71,99,112,74,121,67,48,103,48,84,57,118,84,49,104,97,53,88,111,115,55,108,116,55,110,112,113,117,52,105,56,72,116,112,99,110,111,108,115,81,79,121,85,49,109,56,65,52,73,97,78,67,75,81,109,49,122,116,82,83,82,53,76,43,90,89,73,65,115,52,80,78,78,107,54,74,114,67,109,72,111,99,120,83,51,106,103,51,69,56,87,81,68,65,75,105,65,76,65,68,67,66,76,65,68,65,66,76,73,65,65,66,80,73,65,103,66,77,73,65,115,65,77,73,69,115,65,77,65,69,115,103,65,65,69,56,103,67,65,69,119,103,67,119,65,119,103,83,119,65,119,65,83,121,65,65,65,84,121,65,73,65,84,67,65,76,65,68,67,66,76,65,68,65,66,76,73,65,65,66,80,73,65,103,66,77,73,65,115,65,77,73,69,115,65,77,65,69,115,103,65,65,69,56,103,67,65,69,119,103,67,119,65,119,103,83,119,65,119,65,83,121,65,65,65,84,121,65,73,65,84,67,65,76,65,68,67,66,76,65,68,65,66,76,73,65,65,66,80,73,65,103,66,77,73,65,115,65,77,73,69,115,65,77,65,69,115,103,65,65,65,56,80,119,80,52,47,84,53,75,69,110,102,47,48,84,65,65,65,65,65,69,108,70,84,107,83,117,81,109,67,67,34,125,93,46]}

**Comment by jpgalvao63** [comment]
After the changes you recomendade now i've

![Attachv2_8](https://github.com/chungchunwang/Budibase-File-Upload/assets/157136691/4124da00-f1cb-458e-a69c-4f420a76807f)

**Comment by jpgalvao63** [comment]
Hello,

Sorry to inssist on this.
Do you have any sugestion how to solve the issue ?

BR

**Comment by chungchunwang** [comment]
Hi! Apologies, I had a message, but I failed to send it.

Original:
Hi, based on the data you provided, the file data seems malformed. Was it generated from the file upload plugin?

**Comment by chungchunwang** [comment]
See the following code:
```
let files = []; //List of files items each structured in the following format:
  /*
  {
            name: fileName,
            type: fileType,
            size: fileSize,
            link: linkToFile, //Data URL
          }
  */
```

The file is serialized within a link.

**Comment by chungchunwang** [comment]
Hi, I'm closing this issue for now, but feel free to reopen it if there are any updates.
