### ISSUE TITLE
File Upload to  REST API with a POST call

### ISSUE THREAD

**Issue by tejokrishna** [chungchunwang/Budibase-File-Upload#15]
Hi @chungchunwang ,

 Thank you for making this plugin available. I am trying to use the plugin to post the file with content-type: multipart/form-data. However, I am not able to get it right. Can you please point me to an example for the same please? Thanks in anticipation.

Tejo

**Comment by chungchunwang** [comment]
Hi! The plug-in works essentially as a glorified text field, everything is encoded into plaintext. Thus, the plug-in should fill a text value in a form.

I'm not sure what you mean by filling form-data, maybe it's something new in Budibase I'm not familiar with. However, it can really only fill text fields.

All available documentation for this plug-in is on the GitHub page.

**Comment by chungchunwang** [comment]
Assuming this issue has been solved given the lack of activity. Feel free to reopen if you continue to face any problems.
