### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by Athik321** [chungchunwang/Budibase-File-Upload#17]
The data being stored is very long; can I shorten it? I am using the MySQL database.  And where was the uploaded image stored?

**Comment by chungchunwang** [comment]
The uploaded image/file is stored in the data string - that is why it is so long. Thus, you also cannot shorten the data string.

If you're searching for a solution that stores a file/image in a separate store, look into the default Budibase attachment component. https://docs.budibase.com/docs/attachment. That uploads the file to MinIO and stores a link to the file.

Hope this helps!

Feel free to reopen the issue btw if you have any other questions.

**Comment by Athik321** [comment]
Actually, I am using a MySQL database, and in a form when I use a table from MySQL, can I also use MinIO in the same form?

**Comment by chungchunwang** [comment]
Budibase comes with MinIO installed, thus, the file is stored on whatever server is hosting your Budibase app. 
When you submit a form with the attachment field, it is first stored in MinIO. Then, a url to the file in MinIO is saved to your MySQL. 

I made this plugin as using MinIO made it hard to back things up, so this plugin serializes the entire file as a string and saves it into the SQL server.

**Comment by Athik321** [comment]
When I create a table and want to add an attachment column, the attachment data type is not visible in the data type list.
Do I need to set up MinIO first to make attachment data type visible?

**Comment by chungchunwang** [comment]
Hmm, I'm not sure as I've only used the native attachment component with the Budibase internal DB. Maybe try asking in the discussion board of the Budibase repo? https://github.com/Budibase/budibase/discussions
