### ISSUE TITLE
Disable file preview

### ISSUE THREAD

**Issue by IvanDrag0** [chungchunwang/Budibase-File-Upload#19]
Is there a way to disable file preview in the component? It works great with an image, but with any other file, I just get a big block that says that the preview is not supported.

![image](https://github.com/user-attachments/assets/4ae4a056-3b4c-457d-8b17-88e1fc8273e5)

**Comment by chungchunwang** [comment]
Hi! You could try using the 1.1.9 release, which does not have file preview.

I might push an update that minimizes the box when there is no preview, I can't confirm when I can do that though.

If you can work with the source code, feel free to make a pull request that adds this!

**Comment by IvanDrag0** [comment]
Thank you for the quick response!
