### ISSUE TITLE
Newly uploaded file has an unexpected JSON format

### ISSUE THREAD

**Issue by zedascouves** [chungchunwang/Budibase-File-Upload#21]
Hello!

It seems the previous fix may have introduced another bug. The resulting JSON format is now lacking a ".[" in the beginning and a "]." at the end.

So, previously, it was like:
`.[{"name":"Palete 127_2023 - PN-40.jpg","type":"image/jpeg","size":156205,"link"...}].`

And now it's like:
`{"name":"Palete 127_2023 - PN-40.jpg","type":"image/jpeg","size":156205,"link"...}`

This prevents the file repeater plugin from rendering the image (in my case).

If I add the missing characters, everything works as expected.

Thank you!

**Comment by chungchunwang** [comment]
Is encoding protection turned on for the uploading component?

**Comment by zedascouves** [comment]
It wasn't, silly me...

I've checked the boxes and it's working as expected.

Thank you!
Sent from a calculator.

A terça, 19/11/2024, 01:56, chungchunwang ***@***.***>
escreveu:

**Comment by chungchunwang** [comment]
Okay! Hopefully everything works as normal again then!
Cheeky plug, but if you haven't yet, a star on the repo would be much appreciated!
