### ISSUE TITLE
Minor UI Bug: Overlapping label text

### ISSUE THREAD

**Issue by melohagan** [chungchunwang/Budibase-File-Upload#9]
The label text in the settings panel overlap. 

May be worth shortening the text descriptions of the settings as they are hard to read:

![Screenshot 2023-05-16 at 12 03 54](https://github.com/chungchunwang/Budibase-File-Upload/assets/101575380/c5d74402-49ab-4706-94d6-a726e7d4de1c)

**Comment by chungchunwang** [comment]
This should be fixed now, I've shortened the names.
![image](https://github.com/chungchunwang/Budibase-File-Upload/assets/62127500/c0820143-edd1-45b5-9f86-a82f3f22bd8f)
